### ISSUE TITLE
The DTLD dataset's url was invalid

### ISSUE THREAD

**Issue by qhykwsw** [julimueller/dtld_parsing#1]
I have received the email that contain the download link, but the url was missing.

**Comment by julimueller** [comment]
> I have received the email that contain the download link, but the url was missing.

We had to change the URL during the weekend because of an suspicious event. Now the registration should work again. I have informed everybody who registered during the weekend. For the case I forgot you please send me your E-Mail so that i can give you the new URL. You can also register again to receive the new URL.

Best,

Julian

**Comment by tooHotSpot** [comment]
Could not download whole dataset, downloading error after about 500 Mb of data. Both usual browser download or Linux apps for download (wget, etc) face the problem.
