### ISSUE TITLE
Why is the image I downloaded is .tiff, and there is no color, not RGB.  How can I get RGB color images?

### ISSUE THREAD

**Issue by yangzhaonan18** [julimueller/dtld_parsing#4]
Why is the image I downloaded is .tiff, and there is no color, not RGB. 
How can I get RGB color images?

**Comment by yangzhaonan18** [comment]
import cv2

import numpy as np

file_path = "Berlin/Berlin4/2015-04-17_14-06-56/DE_BBBR667_2015-04-17_14-07-00-506992_k0.tiff"
img = cv2.imread(file_path, cv2.IMREAD_UNCHANGED)
img = cv2.cvtColor(img, cv2.COLOR_BAYER_GB2BGR)
img = np.right_shift(img, 4)
img = img.astype(np.uint8)

print(img)
cv2.imshow("asdf", img)
cv2.waitKey()

**Comment by julimueller** [comment]
Your issue seems to be fixed?

**Comment by luqioayun** [comment]
> Why is the image I downloaded is .tiff, and there is no color, not RGB.
> How can I get RGB color images?

hello, have you solved the problem? I download the image and open it, but it show the black

**Comment by julimueller** [comment]
The 12 bit raw images are stored in 16 bit. Take a look into the parsing modules included in this repository. You first need to convert them to 8 bit in order to visualize them.

**Comment by luqioayun** [comment]
got it, thanks a lot! ^^&nbsp;



祝您身体健康，工作顺利~


鲁巧芸
北京邮电大学
Tel：18612146135
E-mail:1182102020@qq.com
 

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "julimueller/dtld_parsing"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月17日(星期五) 下午3:19
收件人:&nbsp;"julimueller/dtld_parsing"<dtld_parsing@noreply.github.com&gt;;
抄送:&nbsp;"鲁巧芸"<1182102020@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [julimueller/dtld_parsing] Why is the image I downloaded is .tiff, and there is no color, not RGB.  How can I get RGB color images? (#4)





 
The 12 bit raw images are stored in 16 bit. Take a look into the parsing modules included in this repository. You first need to convert them to 8 bit in order to visualize them.
